### ISSUE TITLE
Issues in importing

### ISSUE THREAD

**Issue by steric85** [LinusU/node-render-webpage#1]
I included current version of `render-webpage` in the dependencies in package.json. Now when I write 
```
var renderWebpage = require('render-webpage')
 
renderWebpage('http://google.se', 'google.pdf', function (err) {
  if (err) throw err
 
  console.log('Success!')
})
```
I need to import `render-webpage` . So i wrote `import render-webpage from 'render-webpage'` at the top of the js file. But writing `render-webpage` gives me error. How shall I import?

**Comment by LinusU** [comment]
I think that you should write `import renderWebpage from 'render-webpage'`

**Comment by steric85** [comment]
I tried doing that, but it gives me error :
```
Failed to compile
./~/render-webpage/index.js
Module not found: Can't resolve 'child_process' in '/Users/react-app/node_modules/render-webpage'
```

**Comment by LinusU** [comment]
Are you trying to use this module in a frontend project? This currently only runs under [Node.js](https://nodejs.org)...

**Comment by steric85** [comment]
Oh yes. I was not using NodeJs. Thanks a lot for helping! 😄

**Comment by LinusU** [comment]
No problem!
